server:
  port: 8090
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.203.128:3306/spring_cloud_order?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.203.128:8761/eureka/,http://192.168.203.128:8762/eureka/
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.imooc.order.entity
version: peer1
