server:
  port: 8080
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.203.128:3306/spring_cloud_product?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
mybatis:
  mapper-locations: classpath:mappers/*.xml # 注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.imooc.product.entity # 注意：对应实体类的路径
