server:
  port: 8080
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.203.128:3306/spring_cloud_product?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://192.168.203.128:8761/eureka/
server:
  port: 8080
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.imooc.product.entity
